spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 939014473539-l709kb1kv45dbtdmavi3f8jf7lt6een7.apps.googleusercontent.com
            client-secret: KvidEf_gbQmQKQPTYwHoACuw
            scope:
            - email
            - profile
          facebook:
            client-id: 575414096791057
            client-secret: bebccb1084c3a5386cb2b6f82975aa53
            scope:
              - email
              - public_profile
